// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: agent.proto

package agentv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	api "github.com/Dome-Systems/sdk-dome-go/internal/api"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AgentRegistryName is the fully-qualified name of the AgentRegistry service.
	AgentRegistryName = "dome.agent.v1.AgentRegistry"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AgentRegistryRegisterAgentProcedure is the fully-qualified name of the AgentRegistry's
	// RegisterAgent RPC.
	AgentRegistryRegisterAgentProcedure = "/dome.agent.v1.AgentRegistry/RegisterAgent"
	// AgentRegistryGetAgentProcedure is the fully-qualified name of the AgentRegistry's GetAgent RPC.
	AgentRegistryGetAgentProcedure = "/dome.agent.v1.AgentRegistry/GetAgent"
	// AgentRegistryListAgentsProcedure is the fully-qualified name of the AgentRegistry's ListAgents
	// RPC.
	AgentRegistryListAgentsProcedure = "/dome.agent.v1.AgentRegistry/ListAgents"
	// AgentRegistryUpdateAgentProcedure is the fully-qualified name of the AgentRegistry's UpdateAgent
	// RPC.
	AgentRegistryUpdateAgentProcedure = "/dome.agent.v1.AgentRegistry/UpdateAgent"
	// AgentRegistryRevokeAgentProcedure is the fully-qualified name of the AgentRegistry's RevokeAgent
	// RPC.
	AgentRegistryRevokeAgentProcedure = "/dome.agent.v1.AgentRegistry/RevokeAgent"
	// AgentRegistryHeartbeatProcedure is the fully-qualified name of the AgentRegistry's Heartbeat RPC.
	AgentRegistryHeartbeatProcedure = "/dome.agent.v1.AgentRegistry/Heartbeat"
	// AgentRegistryWatchAgentsProcedure is the fully-qualified name of the AgentRegistry's WatchAgents
	// RPC.
	AgentRegistryWatchAgentsProcedure = "/dome.agent.v1.AgentRegistry/WatchAgents"
)

// AgentRegistryClient is a client for the dome.agent.v1.AgentRegistry service.
type AgentRegistryClient interface {
	RegisterAgent(context.Context, *connect.Request[api.RegisterAgentRequest]) (*connect.Response[api.RegisterAgentResponse], error)
	GetAgent(context.Context, *connect.Request[api.GetAgentRequest]) (*connect.Response[api.GetAgentResponse], error)
	ListAgents(context.Context, *connect.Request[api.ListAgentsRequest]) (*connect.Response[api.ListAgentsResponse], error)
	UpdateAgent(context.Context, *connect.Request[api.UpdateAgentRequest]) (*connect.Response[api.UpdateAgentResponse], error)
	RevokeAgent(context.Context, *connect.Request[api.RevokeAgentRequest]) (*connect.Response[api.RevokeAgentResponse], error)
	Heartbeat(context.Context, *connect.Request[api.HeartbeatRequest]) (*connect.Response[api.HeartbeatResponse], error)
	WatchAgents(context.Context, *connect.Request[api.WatchAgentsRequest]) (*connect.ServerStreamForClient[api.AgentEvent], error)
}

// NewAgentRegistryClient constructs a client for the dome.agent.v1.AgentRegistry service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAgentRegistryClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AgentRegistryClient {
	baseURL = strings.TrimRight(baseURL, "/")
	agentRegistryMethods := api.File_agent_proto.Services().ByName("AgentRegistry").Methods()
	return &agentRegistryClient{
		registerAgent: connect.NewClient[api.RegisterAgentRequest, api.RegisterAgentResponse](
			httpClient,
			baseURL+AgentRegistryRegisterAgentProcedure,
			connect.WithSchema(agentRegistryMethods.ByName("RegisterAgent")),
			connect.WithClientOptions(opts...),
		),
		getAgent: connect.NewClient[api.GetAgentRequest, api.GetAgentResponse](
			httpClient,
			baseURL+AgentRegistryGetAgentProcedure,
			connect.WithSchema(agentRegistryMethods.ByName("GetAgent")),
			connect.WithClientOptions(opts...),
		),
		listAgents: connect.NewClient[api.ListAgentsRequest, api.ListAgentsResponse](
			httpClient,
			baseURL+AgentRegistryListAgentsProcedure,
			connect.WithSchema(agentRegistryMethods.ByName("ListAgents")),
			connect.WithClientOptions(opts...),
		),
		updateAgent: connect.NewClient[api.UpdateAgentRequest, api.UpdateAgentResponse](
			httpClient,
			baseURL+AgentRegistryUpdateAgentProcedure,
			connect.WithSchema(agentRegistryMethods.ByName("UpdateAgent")),
			connect.WithClientOptions(opts...),
		),
		revokeAgent: connect.NewClient[api.RevokeAgentRequest, api.RevokeAgentResponse](
			httpClient,
			baseURL+AgentRegistryRevokeAgentProcedure,
			connect.WithSchema(agentRegistryMethods.ByName("RevokeAgent")),
			connect.WithClientOptions(opts...),
		),
		heartbeat: connect.NewClient[api.HeartbeatRequest, api.HeartbeatResponse](
			httpClient,
			baseURL+AgentRegistryHeartbeatProcedure,
			connect.WithSchema(agentRegistryMethods.ByName("Heartbeat")),
			connect.WithClientOptions(opts...),
		),
		watchAgents: connect.NewClient[api.WatchAgentsRequest, api.AgentEvent](
			httpClient,
			baseURL+AgentRegistryWatchAgentsProcedure,
			connect.WithSchema(agentRegistryMethods.ByName("WatchAgents")),
			connect.WithClientOptions(opts...),
		),
	}
}

// agentRegistryClient implements AgentRegistryClient.
type agentRegistryClient struct {
	registerAgent *connect.Client[api.RegisterAgentRequest, api.RegisterAgentResponse]
	getAgent      *connect.Client[api.GetAgentRequest, api.GetAgentResponse]
	listAgents    *connect.Client[api.ListAgentsRequest, api.ListAgentsResponse]
	updateAgent   *connect.Client[api.UpdateAgentRequest, api.UpdateAgentResponse]
	revokeAgent   *connect.Client[api.RevokeAgentRequest, api.RevokeAgentResponse]
	heartbeat     *connect.Client[api.HeartbeatRequest, api.HeartbeatResponse]
	watchAgents   *connect.Client[api.WatchAgentsRequest, api.AgentEvent]
}

// RegisterAgent calls dome.agent.v1.AgentRegistry.RegisterAgent.
func (c *agentRegistryClient) RegisterAgent(ctx context.Context, req *connect.Request[api.RegisterAgentRequest]) (*connect.Response[api.RegisterAgentResponse], error) {
	return c.registerAgent.CallUnary(ctx, req)
}

// GetAgent calls dome.agent.v1.AgentRegistry.GetAgent.
func (c *agentRegistryClient) GetAgent(ctx context.Context, req *connect.Request[api.GetAgentRequest]) (*connect.Response[api.GetAgentResponse], error) {
	return c.getAgent.CallUnary(ctx, req)
}

// ListAgents calls dome.agent.v1.AgentRegistry.ListAgents.
func (c *agentRegistryClient) ListAgents(ctx context.Context, req *connect.Request[api.ListAgentsRequest]) (*connect.Response[api.ListAgentsResponse], error) {
	return c.listAgents.CallUnary(ctx, req)
}

// UpdateAgent calls dome.agent.v1.AgentRegistry.UpdateAgent.
func (c *agentRegistryClient) UpdateAgent(ctx context.Context, req *connect.Request[api.UpdateAgentRequest]) (*connect.Response[api.UpdateAgentResponse], error) {
	return c.updateAgent.CallUnary(ctx, req)
}

// RevokeAgent calls dome.agent.v1.AgentRegistry.RevokeAgent.
func (c *agentRegistryClient) RevokeAgent(ctx context.Context, req *connect.Request[api.RevokeAgentRequest]) (*connect.Response[api.RevokeAgentResponse], error) {
	return c.revokeAgent.CallUnary(ctx, req)
}

// Heartbeat calls dome.agent.v1.AgentRegistry.Heartbeat.
func (c *agentRegistryClient) Heartbeat(ctx context.Context, req *connect.Request[api.HeartbeatRequest]) (*connect.Response[api.HeartbeatResponse], error) {
	return c.heartbeat.CallUnary(ctx, req)
}

// WatchAgents calls dome.agent.v1.AgentRegistry.WatchAgents.
func (c *agentRegistryClient) WatchAgents(ctx context.Context, req *connect.Request[api.WatchAgentsRequest]) (*connect.ServerStreamForClient[api.AgentEvent], error) {
	return c.watchAgents.CallServerStream(ctx, req)
}

// AgentRegistryHandler is an implementation of the dome.agent.v1.AgentRegistry service.
type AgentRegistryHandler interface {
	RegisterAgent(context.Context, *connect.Request[api.RegisterAgentRequest]) (*connect.Response[api.RegisterAgentResponse], error)
	GetAgent(context.Context, *connect.Request[api.GetAgentRequest]) (*connect.Response[api.GetAgentResponse], error)
	ListAgents(context.Context, *connect.Request[api.ListAgentsRequest]) (*connect.Response[api.ListAgentsResponse], error)
	UpdateAgent(context.Context, *connect.Request[api.UpdateAgentRequest]) (*connect.Response[api.UpdateAgentResponse], error)
	RevokeAgent(context.Context, *connect.Request[api.RevokeAgentRequest]) (*connect.Response[api.RevokeAgentResponse], error)
	Heartbeat(context.Context, *connect.Request[api.HeartbeatRequest]) (*connect.Response[api.HeartbeatResponse], error)
	WatchAgents(context.Context, *connect.Request[api.WatchAgentsRequest], *connect.ServerStream[api.AgentEvent]) error
}

// NewAgentRegistryHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAgentRegistryHandler(svc AgentRegistryHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	agentRegistryMethods := api.File_agent_proto.Services().ByName("AgentRegistry").Methods()
	agentRegistryRegisterAgentHandler := connect.NewUnaryHandler(
		AgentRegistryRegisterAgentProcedure,
		svc.RegisterAgent,
		connect.WithSchema(agentRegistryMethods.ByName("RegisterAgent")),
		connect.WithHandlerOptions(opts...),
	)
	agentRegistryGetAgentHandler := connect.NewUnaryHandler(
		AgentRegistryGetAgentProcedure,
		svc.GetAgent,
		connect.WithSchema(agentRegistryMethods.ByName("GetAgent")),
		connect.WithHandlerOptions(opts...),
	)
	agentRegistryListAgentsHandler := connect.NewUnaryHandler(
		AgentRegistryListAgentsProcedure,
		svc.ListAgents,
		connect.WithSchema(agentRegistryMethods.ByName("ListAgents")),
		connect.WithHandlerOptions(opts...),
	)
	agentRegistryUpdateAgentHandler := connect.NewUnaryHandler(
		AgentRegistryUpdateAgentProcedure,
		svc.UpdateAgent,
		connect.WithSchema(agentRegistryMethods.ByName("UpdateAgent")),
		connect.WithHandlerOptions(opts...),
	)
	agentRegistryRevokeAgentHandler := connect.NewUnaryHandler(
		AgentRegistryRevokeAgentProcedure,
		svc.RevokeAgent,
		connect.WithSchema(agentRegistryMethods.ByName("RevokeAgent")),
		connect.WithHandlerOptions(opts...),
	)
	agentRegistryHeartbeatHandler := connect.NewUnaryHandler(
		AgentRegistryHeartbeatProcedure,
		svc.Heartbeat,
		connect.WithSchema(agentRegistryMethods.ByName("Heartbeat")),
		connect.WithHandlerOptions(opts...),
	)
	agentRegistryWatchAgentsHandler := connect.NewServerStreamHandler(
		AgentRegistryWatchAgentsProcedure,
		svc.WatchAgents,
		connect.WithSchema(agentRegistryMethods.ByName("WatchAgents")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dome.agent.v1.AgentRegistry/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AgentRegistryRegisterAgentProcedure:
			agentRegistryRegisterAgentHandler.ServeHTTP(w, r)
		case AgentRegistryGetAgentProcedure:
			agentRegistryGetAgentHandler.ServeHTTP(w, r)
		case AgentRegistryListAgentsProcedure:
			agentRegistryListAgentsHandler.ServeHTTP(w, r)
		case AgentRegistryUpdateAgentProcedure:
			agentRegistryUpdateAgentHandler.ServeHTTP(w, r)
		case AgentRegistryRevokeAgentProcedure:
			agentRegistryRevokeAgentHandler.ServeHTTP(w, r)
		case AgentRegistryHeartbeatProcedure:
			agentRegistryHeartbeatHandler.ServeHTTP(w, r)
		case AgentRegistryWatchAgentsProcedure:
			agentRegistryWatchAgentsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAgentRegistryHandler returns CodeUnimplemented from all methods.
type UnimplementedAgentRegistryHandler struct{}

func (UnimplementedAgentRegistryHandler) RegisterAgent(context.Context, *connect.Request[api.RegisterAgentRequest]) (*connect.Response[api.RegisterAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dome.agent.v1.AgentRegistry.RegisterAgent is not implemented"))
}

func (UnimplementedAgentRegistryHandler) GetAgent(context.Context, *connect.Request[api.GetAgentRequest]) (*connect.Response[api.GetAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dome.agent.v1.AgentRegistry.GetAgent is not implemented"))
}

func (UnimplementedAgentRegistryHandler) ListAgents(context.Context, *connect.Request[api.ListAgentsRequest]) (*connect.Response[api.ListAgentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dome.agent.v1.AgentRegistry.ListAgents is not implemented"))
}

func (UnimplementedAgentRegistryHandler) UpdateAgent(context.Context, *connect.Request[api.UpdateAgentRequest]) (*connect.Response[api.UpdateAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dome.agent.v1.AgentRegistry.UpdateAgent is not implemented"))
}

func (UnimplementedAgentRegistryHandler) RevokeAgent(context.Context, *connect.Request[api.RevokeAgentRequest]) (*connect.Response[api.RevokeAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dome.agent.v1.AgentRegistry.RevokeAgent is not implemented"))
}

func (UnimplementedAgentRegistryHandler) Heartbeat(context.Context, *connect.Request[api.HeartbeatRequest]) (*connect.Response[api.HeartbeatResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dome.agent.v1.AgentRegistry.Heartbeat is not implemented"))
}

func (UnimplementedAgentRegistryHandler) WatchAgents(context.Context, *connect.Request[api.WatchAgentsRequest], *connect.ServerStream[api.AgentEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("dome.agent.v1.AgentRegistry.WatchAgents is not implemented"))
}
